# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpgaprojects/Basys3_Master.xdc

# Block Designs: bd/uart_fifo/uart_fifo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_fifo || ORIG_REF_NAME==uart_fifo}]

# IP: bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_fifo_fifo_generator_0_0 || ORIG_REF_NAME==uart_fifo_fifo_generator_0_0}]

# XDC: bd/uart_fifo/uart_fifo_ooc.xdc
