# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/tim/fpgaprojects/useful-components/UART/UART.srcs/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xci
# IP: The module: 'uart_fifo_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tim/fpgaprojects/useful-components/UART/UART.srcs/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tim/fpgaprojects/useful-components/UART/UART.srcs/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/tim/fpgaprojects/useful-components/UART/UART.srcs/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xci
# IP: The module: 'uart_fifo_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tim/fpgaprojects/useful-components/UART/UART.srcs/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tim/fpgaprojects/useful-components/UART/UART.srcs/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
